import { execFile } from 'node:child_process';
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { join, relative } from 'node:path';
import { promisify } from 'node:util';
import type { CommandModule } from '../../contract/index.ts';
import review from '../review/index.ts';

const exec = promisify(execFile);

type BacklogItem = { severity: string; file: string; line: number; kind: string; fix: string };

async function readExistingFindings(root: string): Promise<BacklogItem[]> {
  const reports = join(root, 'specs', 'reports');
  let names: string[];
  try {
    names = (await readdir(reports)).filter((name) => /\.(json|md|txt)$/u.test(name));
  } catch {
    return [];
  }
  const items: BacklogItem[] = [];
  for (const name of names) {
    const path = join(reports, name);
    let text = '';
    try {
      text = await readFile(path, 'utf8');
    } catch {
      continue;
    }
    try {
      const value = JSON.parse(text) as unknown;
      const visit = (node: unknown): void => {
        if (Array.isArray(node)) {
          for (const child of node) visit(child);
          return;
        }
        if (!node || typeof node !== 'object') return;
        const row = node as Record<string, unknown>;
        if (typeof row.file === 'string' && typeof row.fix === 'string') {
          items.push({
            severity: typeof row.severity === 'string' ? row.severity : 'MEDIUM',
            file: row.file,
            line: typeof row.line === 'number' ? row.line : 1,
            kind: typeof row.kind === 'string' ? row.kind : 'tdd',
            fix: row.fix,
          });
        }
        for (const child of Object.values(row)) visit(child);
      };
      visit(value);
    } catch {
      for (const line of text.split(/\r?\n/u)) {
        const match = /^- \[ \] (?:(CRITICAL|HIGH|MEDIUM|LOW) · )?([^:]+):(\d+) · ([^·]+) · (.+)$/u.exec(line);
        if (match)
          items.push({
            severity: match[1] ?? 'MEDIUM',
            file: match[2] ?? 'unknown',
            line: Number(match[3]),
            kind: match[4]?.trim() ?? 'tdd',
            fix: match[5]?.trim() ?? 'inspect and fix',
          });
      }
    }
  }
  return items;
}

function domainFor(file: string): string {
  const normalized = file.replaceAll('\\', '/');
  const parts = normalized.split('/');
  if (parts[0] === 'apps' || parts[0] === 'packages') return parts.slice(0, 2).join('/') || 'shared';
  return parts[0] && !['scripts', 'specs'].includes(parts[0]) ? parts[0] : 'shared';
}

const audit: CommandModule = {
  verb: 'audit',
  async run(ctx, args) {
    const target = args.positionals.find((value) => !value.startsWith('--'));
    if (target === undefined && args.positionals.length > 0) return 2;
    await mkdir(join(ctx.cwd, 'specs', 'reports'), { recursive: true });
    const gatePath = join(ctx.cwd, 'specs', 'reports', 'audit-gates.txt');
    let gate = '';
    try {
      const result = await exec('git', ['diff', '--check'], { cwd: ctx.cwd, maxBuffer: 1_000_000 });
      gate = result.stdout || 'git diff --check: clean\n';
    } catch (error) {
      gate = `${error instanceof Error ? error.message : String(error)}\n`;
    }
    await writeFile(gatePath, gate, 'utf8');
    const findings = (await readExistingFindings(ctx.cwd))
      .filter((item) => target === undefined || item.file.includes(target) || domainFor(item.file) === target)
      .filter((item, index, all) => all.findIndex((other) => JSON.stringify(other) === JSON.stringify(item)) === index)
      .sort((a, b) => a.severity.localeCompare(b.severity) || a.file.localeCompare(b.file) || a.line - b.line);
    const grouped = new Map<string, BacklogItem[]>();
    for (const item of findings) {
      const domain = domainFor(item.file);
      grouped.set(domain, [...(grouped.get(domain) ?? []), item]);
    }
    const backlog = ['# Refactor backlog', '', `> Generated by cohorte audit (${ctx.clock.now()}).`];
    for (const [domain, items] of [...grouped.entries()].sort(([a], [b]) => a.localeCompare(b))) {
      backlog.push('', `## ${domain}`, '');
      for (const item of items)
        backlog.push(`- [ ] ${item.severity} · ${item.file}:${item.line} · ${item.kind} · ${item.fix}`);
    }
    if (findings.length === 0) backlog.push('', 'No open findings were recovered from the durable reports.', '');
    const backlogPath = join(ctx.cwd, 'specs', 'refactor-backlog.md');
    await writeFile(backlogPath, `${backlog.join('\n')}\n`, 'utf8');
    const result = await review.run(ctx, {
      ...args,
      positionals: target ? [target, ...args.positionals.filter((x) => x.startsWith('--'))] : args.positionals,
    });
    ctx.stdio.stdout.write(
      `audit gates written to ${relative(ctx.cwd, gatePath)}; backlog written to ${relative(ctx.cwd, backlogPath)}; review dispatched\n`,
    );
    return result;
  },
};

export default audit;
