#!/usr/bin/env node
// PLAN §3 rule 5: every unit gets a private, non-emitting TypeScript project that sees ONLY the
// TypeScript it owns. This script derives tsconfig.checks/<unit>.json from docs/v3/plan.json.
// scripts/unit-check.ts runs `tsc -p` on it and downgrades diagnostics located outside the unit's
// owned paths to warnings, so a sibling's half-written file cannot fail your check.
//
//   node scripts/gen-unit-checks.ts            write (and delete files of units that left the plan)
//   node scripts/gen-unit-checks.ts --check    write nothing; exit 1 when tsconfig.checks/ is stale
//   … [--root <dir>] [--plan <file>]           <file> is relative to the root, or absolute; exit 2 when it
//                                              is missing or is not JSON
//
// tsconfig.checks/** is a structural path: only Wave 0 and the integrators run this in write mode.

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { parseArgs } from 'node:util';

export interface PlanUnit {
  id: string;
  ownedPaths: string[];
  testPaths?: string[];
}

export interface Plan {
  waves: Array<{ units: PlanUnit[] }>;
}

export const PLAN_PATH = 'docs/v3/plan.json';
export const CHECKS_DIRECTORY = 'tsconfig.checks';
/** Same exclusions as every other tsconfig, vitest and Biome (PLAN §3 rule 12), plus tsc's own output. */
export const SHARED_EXCLUDES: readonly string[] = [
  'legacy/**',
  '.cohorte/**',
  '.build/**',
  '**/dist/**',
  '**/dist-types/**',
  '**/node_modules/**',
];

const GENERATED_FILE = /^U\d+\.[A-Za-z0-9]+\.json$/;
const TYPESCRIPT_FILE = /\.[cm]?tsx?$/;
/** Top-level directories in which a `dir/**` owned path can hold TypeScript. */
const TYPESCRIPT_ROOTS = new Set(['apps', 'packages', 'scripts', 'tests', 'fixtures']);

/** The plan file is missing or unreadable as JSON: a usage error (exit 2) for both command lines, not a crash. */
export class PlanFileError extends Error {}

/** `planPath` is relative to `root`, or absolute (`--plan` takes either). */
export function loadPlan(root: string, planPath: string = PLAN_PATH): Plan {
  const file = resolve(root, planPath);
  let text: string;
  try {
    text = readFileSync(file, 'utf8');
  } catch (error) {
    if (error instanceof Error && 'code' in error && error.code === 'ENOENT')
      throw new PlanFileError(`plan file not found: ${file}`);
    throw error;
  }
  try {
    return JSON.parse(text) as Plan;
  } catch (error) {
    throw new PlanFileError(`${file} is not valid JSON: ${error instanceof Error ? error.message : String(error)}`);
  }
}

export function unitsOf(plan: Plan): PlanUnit[] {
  return plan.waves.flatMap((wave) => wave.units);
}

/** The owned paths that can hold TypeScript, as `include` patterns relative to tsconfig.checks/. */
export function typeScriptIncludes(ownedPaths: readonly string[]): string[] {
  const includes: string[] = [];
  for (const owned of ownedPaths) {
    const top = owned.split('/')[0] ?? '';
    if (TYPESCRIPT_FILE.test(owned)) {
      if (TYPESCRIPT_ROOTS.has(top) || !owned.includes('/')) includes.push(`../${owned}`);
    } else if (owned.endsWith('/**') && TYPESCRIPT_ROOTS.has(top)) {
      includes.push(`../${owned}/*`);
    }
  }
  return includes;
}

export function renderUnitCheckConfig(unit: PlanUnit): string {
  const include = typeScriptIncludes(unit.ownedPaths);
  const config = {
    $comment: `GENERATED by scripts/gen-unit-checks.ts from ${PLAN_PATH} (unit ${unit.id}). Do not edit: change the plan and regenerate.`,
    extends: '../tsconfig.base.json',
    compilerOptions: {
      composite: false,
      declaration: false,
      declarationMap: false,
      emitDeclarationOnly: false,
      incremental: false,
      noEmit: true,
    },
    // `files: []` keeps a unit that owns no TypeScript from matching anything by default.
    ...(include.length === 0 ? { files: [] } : {}),
    include,
    exclude: SHARED_EXCLUDES.map((pattern) => `../${pattern}`),
  };
  return `${JSON.stringify(config, null, 2)}\n`;
}

export interface GenerateResult {
  written: string[];
  removed: string[];
  /** --check only: files that are missing, different, or belong to no unit of the plan. */
  stale: string[];
}

export function generateUnitChecks(options: { root: string; planPath?: string; check?: boolean }): GenerateResult {
  const { root, check = false } = options;
  const directory = join(root, CHECKS_DIRECTORY);
  const expected = new Map(
    unitsOf(loadPlan(root, options.planPath)).map((unit) => [`${unit.id}.json`, renderUnitCheckConfig(unit)]),
  );
  const present = existsSync(directory) ? readdirSync(directory).filter((name) => GENERATED_FILE.test(name)) : [];
  const result: GenerateResult = { written: [], removed: [], stale: [] };
  const relativeName = (name: string) => `${CHECKS_DIRECTORY}/${name}`;

  for (const [name, content] of expected) {
    const path = join(directory, name);
    const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
    if (current === content) continue;
    if (check) {
      result.stale.push(relativeName(name));
    } else {
      mkdirSync(directory, { recursive: true });
      writeFileSync(path, content);
      result.written.push(relativeName(name));
    }
  }
  for (const name of present.filter((candidate) => !expected.has(candidate))) {
    if (check) {
      result.stale.push(relativeName(name));
    } else {
      rmSync(join(directory, name));
      result.removed.push(relativeName(name));
    }
  }
  return result;
}

function main(): number {
  const { values } = parseArgs({
    options: { root: { type: 'string' }, plan: { type: 'string' }, check: { type: 'boolean', default: false } },
  });
  const root = resolve(values.root ?? join(import.meta.dirname, '..'));
  let result: GenerateResult;
  try {
    result = generateUnitChecks({ root, check: values.check, ...(values.plan ? { planPath: values.plan } : {}) });
  } catch (error) {
    if (!(error instanceof PlanFileError)) throw error;
    process.stderr.write(`gen-unit-checks: ${error.message}\n`);
    process.stderr.write('usage: node scripts/gen-unit-checks.ts [--check] [--root <dir>] [--plan <file>]\n');
    return 2;
  }
  if (values.check) {
    if (result.stale.length === 0) {
      process.stdout.write(`gen-unit-checks: ${CHECKS_DIRECTORY}/ matches ${values.plan ?? PLAN_PATH}\n`);
      return 0;
    }
    for (const name of result.stale) process.stderr.write(`stale: ${name}\n`);
    process.stderr.write('gen-unit-checks: run `node scripts/gen-unit-checks.ts` (integrators and Wave 0 only)\n');
    return 1;
  }
  process.stdout.write(`gen-unit-checks: ${result.written.length} written, ${result.removed.length} removed\n`);
  return 0;
}

if (import.meta.main) process.exitCode = main();
